# This is a workflow for testing various Nuitka command-line options

name: Build-All-Platforms

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
     strategy:
        matrix:
          #os: [macos-latest, ubuntu-latest, windows-latest]
          os: [ubuntu-latest, windows-latest]
  
     runs-on: ${{ matrix.os }}
  
     steps:
        - name: Check-out repository
          uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
             python-version: '3.10'
             cache: 'pip'
             cache-dependency-path: |
                **/requirements*.txt
    
        - name: Install your Dependencies
          run: |
             pip install -r requirements.txt -r requirements-dev.txt
    
        - name: Build Executable with Nuitka
          uses: Nuitka/Nuitka-Action@main
          with:
             nuitka-version: main
             script-name: can_testbench.py
             # many more Nuitka options available, see action doc, but it's best
             # to use nuitka-project: options in your code, so e.g. you can make
             # a difference for macOS and create an app bundle there.
    
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
             name: ${{ runner.os }} Build
             path: | # Upload dist folder
                dist/
